backend/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from backend import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shoppingcart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^products/(?<product_id>\d+)/add/$', views.add_product, name='add_product'),
    (r'cart/view/', views.view_cart),
)

shoppingcart/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shoppingcart.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('backend.urls', namespace='backend')),
    url(r'^cart/', include('fastcart.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/models.py
# -*-coding=utf-8-*-
from django.db import models
from django.utils.timezone import now

class Product(models.Model):
    name           = models.CharField(max_length=100)
    brand_type     = models.TextField()
    description    = models.TextField(null=True, blank=True)
    create_time    = models.DateTimeField(default=now)
    update_time    = models.DateTimeField(auto_now=True)

    def get_price_list(self):
        return Price.objects.filter(product=self)

    def __unicode__(self):
        return u"%d-%s" % (self.id if self.id  is not None else 0, self.name)


class Price(models.Model):
    HIGH = 'high'
    STANDARD = 'standard'
    LOW = 'low'

    CONFIG_CHOICES = (
        (HIGH, u'高配'),
        (STANDARD, u'标配'),
        (LOW, u'低配')  
    )

    product = models.ForeignKey(Product)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    config_type = models.CharField(max_length=10, choices=CONFIG_CHOICES, default=STANDARD)
    create_time    = models.DateTimeField(default=now)
    update_time    = models.DateTimeField(auto_now=True)

        


# class  LineItem(models.Model):
#     prduct = models.ForeignKey(Product)
#     unit_price = models.DecimalField(max_digits=10, decimal_places=2)
#     quantity = models.IntegerField()


# class Cart(object):  
#     def __init__(self, *args, **kwargs):  
#         self.items = []  
#         self.total_price = 0  
#     def add_product(self, product):  
#         self.total_price += product.price  
#         for item in self.items:  
#             if item.product.id == product.id:  
#                 item.quantity += 1   
#                 return  
#         self.items.append(LineItem(product=product,unit_price=product.price,quantity=1))

backend/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect

from .models import Product, Price
from fastcart.models import Cart, CartManager


@csrf_protect
def view_cart(request):
    # cart = request.session.get("cart", None)
    product_list =  list(Product.objects.all())
    # cartManager = CartManager()
    # cart = cartManager.get_for_request(request)
    cart = Cart()
    cart.save()

    for product in product_list:
        cart.add(product)
        # price_dict('product_id') = price.product.id
        # price_list = Price.objects.filter(product__in=product_li
    cart.save()
    # for item in cart.get_items():
    #     config_list = item.get_config_type_list()
    #     import pdb;pdb.set_trace()

    # for price in price_list:
    #     price_dict('product_id') = price.product.id
    #     price_dict('unit_price') = price.unit_price

    # import pdb;pdb.set_trace()

  
    # if not cart:  
    #     cart = Cart()  
        # request.session["cart"] = json.dumps(cart)
                   
    return render(request, 'base.html', {'cart': cart})

backend/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ch">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="apple-touch-fullscreen" content="YES">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>配置单计算器</title>
    <link rel="stylesheet" type="text/css" href="{% static 'wap/css/hunting_doctor/main.css' %}"/>
    <script src="http://libs.baidu.com/jquery/1.10.0/jquery.js"></script>
  <style>
    .brand_type { 
      width:50%;
    }

</style>
  <script>
      $(document).ready(function(){
      //     $(".add").click(function(){
      //         var n=$("#quantity").val();
      //             var num=parseInt(n)+1;
      //         if(num==0){alert("cc");
      //        }
      //         $("#quantity").val(num);
      //       });
             $(".cb").change(function(){
                caculate_totoal_price();

             });
            $("#cb_all").change(function(){
                $(".quantity_text").each(function()
                {
                  checkbox_id = "#cb_"+$(this).attr("item_id");
                  $(checkbox_id)[0].checked = $("#cb_all")[0].checked;
                });
                caculate_totoal_price();   

             });

      });

      function quantity_text_change(id){
        value = $("#"+id).val().replace(/[^\d]/g,'')
        $("#"+id).val(value);
        if ($("#"+id).val() <= 0 || $("#"+id).val() == "") {
          $("#"+id).val(1);
        }
        caculate_totoal_price();

      }
      function sub(quantity_id){
          var n=$("#"+quantity_id).val();
          var num=parseInt(n)-1;
          if(num==0){alert("不能为0!"); return}
          $("#"+quantity_id).val(num);
          caculate_totoal_price();
          }

      function add(quantity_id){
          var n=$("#"+quantity_id).val();
          var num=parseFloat(n)+1;
          if(num==0){alert("cc");
             }
          $("#"+quantity_id).val(num);
          caculate_totoal_price();
      }

      function caculate_totoal_price(){
           total_price = 0;
           $(".quantity_text").each(function()
            {
              item_id = $(this).attr("item_id")
              if($("#cb_"+item_id)[0].checked==true){
                unit_price = $("#se_"+item_id).find("option:selected").attr('data_unit_price');
                total_price += parseInt($(this).val()) * parseFloat(unit_price);
            }

            });
           $("#total_price").text(total_price.toFixed(2));

      }
  </script>
</head>

<body class="hunting_result">
<!--         <div class="product_list">
        {% for product in product_list %}
          <input type="button" value="{{product.name}}"/>

        {% endfor %}
        </div> -->
    <form action="{% url 'fastcart_cart_item_update' cart.pk %}" method="post">
        {% csrf_token %}
        <div class="result">
            <div class="row"> 

                  <div class="span10">  
                    <table class="condensed-table">  
                      <thead>  
                        <tr>
                          <th><input  type='checkbox' id='cb_all' checked="ture">全选</th>
                          <th class="header">配件</th>  
                          <th class="yellow header">品牌/型号</th>
                          <th class="yellow header">配置</th>   
                          <th class="blue header">数量</th>  
                          <th class="green header">价格</th>  
                        </tr>  
                      </thead>  
                      <tbody>  
                      {% for item in cart.get_items %}  
                        <tr> 
                          <th><input id="cb_{{item.pk}}" class="cb" type='checkbox' checked="ture"></th> 
                          <td>{{item.product.name}}</td>  
                          <td class="brand_type">{{item.product.brand_type}}</td> 
                          <td>
                          <select id="se_{{item.pk}}">
                            {% for price in item.product.get_price_list %}
                                {% if price == item.price %}
                                    <option data_unit_price={{price.unit_price}} value={{price.config_type}} selected="selected">{{price.get_config_type_display}}
                                    </option>
                                {% else %}
                                    <option data_unit_price={{price.unit_price}} value={{price.config_type}} >{{price.get_config_type_display}}
                                    </option>
                                {% endif %}
                            {% endfor %}
                            <script>
                                $("#se_{{item.pk}}").change(function(){
                                  caculate_totoal_price();
                                  unit_price = parseFloat($("#se_{{item.pk}}").find("option:selected").attr('data_unit_price')).toFixed(2);
                                  $("#unit_price_{{item.pk}}").text(unit_price);

                                });

                            </script>
                          </select>
                          </td>
                          <td>   
                                <input type='button' class="sub"  value='-' onClick="sub('quantity_{{item.pk}}')">
                                <input class='quantity_text' item_id="{{item.pk}}" data_price="{{item.product.price}}" id="quantity_{{item.pk}}" name="quantity" onkeyup="quantity_text_change('quantity_{{item.pk}}')" value="{{ item.quantity }}" 
                                onbeforepaste="clipboardData.setData('text',clipboardData.getData('text').replace(/[^\d]/g,''))">
                                <input type='button' class='add' onClick="add('quantity_{{item.pk}}')" value='+' >

                          </td>
                          <td id="unit_price_{{item.pk}}">{{item.unit_price}}</td>  
                        </tr>  
                      {% endfor %}  
                        <tr>  
                          <th></th>  
                          <td></td>  
                          <th>总计：</th>  
          
                          <th id="total_price">{{cart.get_total_price}}</th>  
                        </tr>  
                      </tbody>  
                    </table>  
                      
          
                  </div>  
                  <div class="submit">  
                    <input type="submit" value="保存"> 
                    <input type="button" value="电话咨询">
                      
                  </div>  
                </div>  
        </div>
    </form>

</body>
</html>

backend/templates/view_cart.html
    {% extends "base.html" %}  
      
    {% block title %} 我的购物车{% endblock %}  
      
    {% block pagename %} 我的购物车  {% endblock %}  
      
    {% block content %}   
    <div class="row">  
              <div class="span10">  
                <table class="condensed-table">  
                  <thead>  
                    <tr>  
                      <th class="header">数量</th>  
                      <th class="yellow header">名称</th>  
                      <th class="blue header">单价</th>  
      
                      <th class="green header">小计</th>  
                    </tr>  
                  </thead>  
                  <tbody>  
                  {% for item in cart.items %}  
                    <tr>  
                      <th>{{item.quantity}}</th>  
                      <td>{{item.product.title}}</td>  
      
                      <td>{{item.unit_price}}</td>  
                      <td>{% widthratio item.quantity 1 item.unit_price %} </td>  
                    </tr>  
                  {% endfor %}  
                    <tr>  
                      <th></th>  
                      <td></td>  
                      <th>总计：</th>  
      
                      <th>{{cart.total_price}}</th>  
                    </tr>  
                  </tbody>  
                </table>  
                  
      
              </div>  
              <div class="span4">  
                <p><a class="btn primary span2" href="#">继续购物</a></a> </p>  
                <p><a class="btn danger span2" href="#">清空购物车</a></p>  
                <p><a class="btn success span2" href="#">结算</a> </p>  
                  
              </div>  
            </div>  
    {% endblock %}  